onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -format Logic -label "x" {/fpga_top_tb/dut/io_0_1/inpad[0]}
add wave -noupdate -format Logic -label "out:g1" {/fpga_top_tb/dut/io_0_1/outpad[2]}
add wave -noupdate -format Logic -label "y" {/fpga_top_tb/dut/io_0_1/inpad[3]}
add wave -noupdate -format Logic -label "out:f1" {/fpga_top_tb/dut/io_0_1/outpad[7]}
add wave -noupdate -format Logic -label "out:s0" {/fpga_top_tb/dut/io_0_2/outpad[2]}
add wave -noupdate -format Logic -label "v" {/fpga_top_tb/dut/io_0_2/inpad[4]}
add wave -noupdate -format Logic -label "out:x0" {/fpga_top_tb/dut/io_0_3/outpad[0]}
add wave -noupdate -format Logic -label "f0" {/fpga_top_tb/dut/io_0_3/inpad[1]}
add wave -noupdate -format Logic -label "p" {/fpga_top_tb/dut/io_0_3/inpad[3]}
add wave -noupdate -format Logic -label "h0" {/fpga_top_tb/dut/io_0_3/inpad[4]}
add wave -noupdate -format Logic -label "out:r0" {/fpga_top_tb/dut/io_0_3/outpad[5]}
add wave -noupdate -format Logic -label "r" {/fpga_top_tb/dut/io_0_3/inpad[6]}
add wave -noupdate -format Logic -label "e0" {/fpga_top_tb/dut/io_0_4/inpad[1]}
add wave -noupdate -format Logic -label "k0" {/fpga_top_tb/dut/io_0_4/inpad[2]}
add wave -noupdate -format Logic -label "g0" {/fpga_top_tb/dut/io_0_4/inpad[3]}
add wave -noupdate -format Logic -label "j" {/fpga_top_tb/dut/io_0_4/inpad[4]}
add wave -noupdate -format Logic -label "out:q0" {/fpga_top_tb/dut/io_0_4/outpad[6]}
add wave -noupdate -format Logic -label "c" {/fpga_top_tb/dut/io_0_5/inpad[7]}
add wave -noupdate -format Logic -label "b" {/fpga_top_tb/dut/io_1_0/inpad[1]}
add wave -noupdate -format Logic -label "w" {/fpga_top_tb/dut/io_1_0/inpad[3]}
add wave -noupdate -format Logic -label "out:w0" {/fpga_top_tb/dut/io_2_0/outpad[1]}
add wave -noupdate -format Logic -label "d" {/fpga_top_tb/dut/io_2_0/inpad[2]}
add wave -noupdate -format Logic -label "o" {/fpga_top_tb/dut/io_2_0/inpad[7]}
add wave -noupdate -format Logic -label "out:j1" {/fpga_top_tb/dut/io_2_6/outpad[1]}
add wave -noupdate -format Logic -label "out:h1" {/fpga_top_tb/dut/io_2_6/outpad[6]}
add wave -noupdate -format Logic -label "out:t0" {/fpga_top_tb/dut/io_3_0/outpad[1]}
add wave -noupdate -format Logic -label "a" {/fpga_top_tb/dut/io_3_0/inpad[2]}
add wave -noupdate -format Logic -label "m0" {/fpga_top_tb/dut/io_3_0/inpad[5]}
add wave -noupdate -format Logic -label "out:u0" {/fpga_top_tb/dut/io_3_0/outpad[6]}
add wave -noupdate -format Logic -label "z" {/fpga_top_tb/dut/io_3_0/inpad[7]}
add wave -noupdate -format Logic -label "i" {/fpga_top_tb/dut/io_3_6/inpad[0]}
add wave -noupdate -format Logic -label "j0" {/fpga_top_tb/dut/io_3_6/inpad[1]}
add wave -noupdate -format Logic -label "out:i1" {/fpga_top_tb/dut/io_3_6/outpad[4]}
add wave -noupdate -format Logic -label "out:a1" {/fpga_top_tb/dut/io_3_6/outpad[5]}
add wave -noupdate -format Logic -label "d0" {/fpga_top_tb/dut/io_3_6/inpad[6]}
add wave -noupdate -format Logic -label "c0" {/fpga_top_tb/dut/io_3_6/inpad[7]}
add wave -noupdate -format Logic -label "s" {/fpga_top_tb/dut/io_4_0/inpad[0]}
add wave -noupdate -format Logic -label "out:v0" {/fpga_top_tb/dut/io_4_0/outpad[1]}
add wave -noupdate -format Logic -label "t" {/fpga_top_tb/dut/io_4_0/inpad[2]}
add wave -noupdate -format Logic -label "u" {/fpga_top_tb/dut/io_4_0/inpad[4]}
add wave -noupdate -format Logic -label "f" {/fpga_top_tb/dut/io_4_6/inpad[1]}
add wave -noupdate -format Logic -label "out:d1" {/fpga_top_tb/dut/io_4_6/outpad[4]}
add wave -noupdate -format Logic -label "i0" {/fpga_top_tb/dut/io_5_0/inpad[7]}
add wave -noupdate -format Logic -label "a0" {/fpga_top_tb/dut/io_6_1/inpad[3]}
add wave -noupdate -format Logic -label "out:y0" {/fpga_top_tb/dut/io_6_1/outpad[4]}
add wave -noupdate -format Logic -label "l" {/fpga_top_tb/dut/io_6_1/inpad[5]}
add wave -noupdate -format Logic -label "out:e1" {/fpga_top_tb/dut/io_6_2/outpad[0]}
add wave -noupdate -format Logic -label "g" {/fpga_top_tb/dut/io_6_2/inpad[1]}
add wave -noupdate -format Logic -label "m" {/fpga_top_tb/dut/io_6_2/inpad[5]}
add wave -noupdate -format Logic -label "l0" {/fpga_top_tb/dut/io_6_3/inpad[0]}
add wave -noupdate -format Logic -label "out:c1" {/fpga_top_tb/dut/io_6_3/outpad[2]}
add wave -noupdate -format Logic -label "h" {/fpga_top_tb/dut/io_6_3/inpad[5]}
add wave -noupdate -format Logic -label "out:z0" {/fpga_top_tb/dut/io_6_3/outpad[7]}
add wave -noupdate -format Logic -label "out:p0" {/fpga_top_tb/dut/io_6_4/outpad[1]}
add wave -noupdate -format Logic -label "k" {/fpga_top_tb/dut/io_6_4/inpad[4]}
add wave -noupdate -format Logic -label "b0" {/fpga_top_tb/dut/io_6_4/inpad[5]}
add wave -noupdate -format Logic -label "q" {/fpga_top_tb/dut/io_6_4/inpad[6]}
add wave -noupdate -format Logic -label "out:b1" {/fpga_top_tb/dut/io_6_4/outpad[7]}
add wave -noupdate -format Logic -label "n0" {/fpga_top_tb/dut/io_6_5/inpad[0]}
add wave -noupdate -format Logic -label "o0" {/fpga_top_tb/dut/io_6_5/inpad[4]}
add wave -noupdate -format Logic -label "e" {/fpga_top_tb/dut/io_6_5/inpad[5]}
add wave -noupdate -format Logic -label "n" {/fpga_top_tb/dut/io_6_5/inpad[6]}
add wave -noupdate -format Literal -group "g1" /fpga_top_tb/dut/clb_1_1/*
add wave -noupdate -format Literal -group "\[63\]" /fpga_top_tb/dut/clb_1_3/*
add wave -noupdate -format Literal -group "\[237\]" /fpga_top_tb/dut/clb_1_4/*
add wave -noupdate -format Literal -group "\[70\]" /fpga_top_tb/dut/clb_1_5/*
add wave -noupdate -format Literal -group "w0" /fpga_top_tb/dut/clb_2_1/*
add wave -noupdate -format Literal -group "s0" /fpga_top_tb/dut/clb_2_2/*
add wave -noupdate -format Literal -group "\[258\]" /fpga_top_tb/dut/clb_2_3/*
add wave -noupdate -format Literal -group "\[23\]" /fpga_top_tb/dut/clb_2_4/*
add wave -noupdate -format Literal -group "h1" /fpga_top_tb/dut/clb_2_5/*
add wave -noupdate -format Literal -group "\[40\]" /fpga_top_tb/dut/clb_3_1/*
add wave -noupdate -format Literal -group "\[34\]" /fpga_top_tb/dut/clb_3_2/*
add wave -noupdate -format Literal -group "z0" /fpga_top_tb/dut/clb_3_3/*
add wave -noupdate -format Literal -group "\[49\]" /fpga_top_tb/dut/clb_3_4/*
add wave -noupdate -format Literal -group "na1" /fpga_top_tb/dut/clb_3_5/*
add wave -noupdate -format Literal -group "\[249\]" /fpga_top_tb/dut/clb_4_1/*
add wave -noupdate -format Literal -group "c1" /fpga_top_tb/dut/clb_4_3/*
add wave -noupdate -format Literal -group "\[48\]" /fpga_top_tb/dut/clb_4_4/*
add wave -noupdate -format Literal -group "\[242\]" /fpga_top_tb/dut/clb_4_5/*
add wave -noupdate -format Literal -group "y0" /fpga_top_tb/dut/clb_5_1/*
add wave -noupdate -format Literal -group "\[55\]" /fpga_top_tb/dut/clb_5_2/*
add wave -noupdate -format Literal -group "\[243\]" /fpga_top_tb/dut/clb_5_3/*
add wave -noupdate -format Literal -group "p0" /fpga_top_tb/dut/clb_5_4/*
add wave -noupdate -format Literal -group "\[253\]" /fpga_top_tb/dut/clb_5_5/*
